nicks = [
  {nick:'Foxkrak',all:true,autoup:true,agtk:true,autocol:true,venderpp:true},
  {nick:'foxkrakx',all:true,autoup:true,agtk:true,autocol:true,venderpp:true},
  {nick:'junior72',all:true,autoup:true,agtk:true,autocol:true,venderpp:true},
  {nick:'BLACK SNIPER',all:true,autoup:true,agtk:true,autocol:true,venderpp:true},
  {nick:'stromrakka',all:true,autoup:true,agtk:true,autocol:true,venderpp:true},
  {nick:'Filho de Zeus',all:true,autoup:true,agtk:true,autocol:true,venderpp:true}, // Não ta moralizado.
  {nick:'igor89araujo',all:true,autoup:true,agtk:true,autocol:true,venderpp:true},
  {nick:'Frost',all:true,autoup:true,agtk:true,autocol:true,venderpp:true},
  {nick:'WBPinto',all:true,autoup:true,agtk:true,autocol:true,venderpp:true},
  {nick:'xxxhygorxxx',all:true,autoup:true,agtk:true,autocol:true,venderpp:true},
  {nick:'chuck.mauricio',all:true,autoup:true,agtk:false,autocol:true,venderpp:true},
  {nick:'tutancamon',all:true,autoup:true,agtk:true,autocol:true,venderpp:true},
  {nick:'matheusass',all:true,autoup:true,agtk:true,autocol:true,venderpp:true},
  {nick:'- Os Rauls',all:true,autoup:true,agtk:true,autocol:true,venderpp:true},
  {nick:'sdrago',all:true,autoup:true,agtk:true,autocol:true,venderpp:true},
  {nick:'joloirao',all:true,autoup:true,agtk:true,autocol:true,venderpp:true},
  {nick:'Leo17Matador',all:true,autoup:true,agtk:true,autocol:true,venderpp:true},
  {nick:'Mano Tse-Tung',all:false,autoup:true,agtk:false,autocol:false,venderpp:false},
  {nick:'Manowar',all:false,autoup:true,agtk:false,autocol:false,venderpp:false},
  {nick:'What Time Is It?',all:false,autoup:false,agtk:true,autocol:false,venderpp:false},
  {nick:'lissim121',all:false,autoup:false,agtk:true,autocol:false,venderpp:false},
  {nick:'Feelipe',all:false,autoup:false,agtk:true,autocol:false,venderpp:false},
  {nick:'Lucas98M',all:false,autoup:false,agtk:true,autocol:false,venderpp:false},
  {nick:'gabrielminatto',all:false,autoup:false,agtk:true,autocol:true,venderpp:false},
  {nick:'fulampa',all:false,autoup:false,agtk:true,autocol:false,venderpp:false},
  {nick:'mateusiglesias',all:false,autoup:false,agtk:true,autocol:false,venderpp:false},
  {nick:'Elindor',all:false,autoup:false,agtk:true,autocol:false,venderpp:false}
]
